### ISSUE TITLE
can you explain me this please?

### ISSUE THREAD

**Issue by harshitwalia** [hichetu/ProgrammersBookshelf#7]
#if _MSC_VER >=	1700
	end = chrono::system_clock::now();
	chrono::duration<double> elapsed_seconds = end-start;
	cout <<"\n"<<endl;
	cout << "elapsed time: " << elapsed_seconds.count() << "s\n";
#endif //what does this do

**Comment by hichetu** [comment]
That piece of code provides the program elapsed time between the 'start' and 'end' code block. 

The code had made use of Chrono time libraries that was only available in Microsoft C++ compiler version > 1700.

So, I used a compiler preprocessor check and enabled that piece of code only when Microsoft C++ compiler version was greater than 1700.

[ Microsoft Visual Studio Compiler Versions](http://stackoverflow.com/questions/70013/how-to-detect-if-im-compiling-code-with-visual-studio-2008)

**Comment by harshitwalia** [comment]
Thanks.
