### ISSUE TITLE
what are pre-requisite i should first learn?

### ISSUE THREAD

**Issue by harshitwalia** [hichetu/ProgrammersBookshelf#8]
Your code is so advanced that i m not able to understand few things.Can you please help me out

**Comment by hichetu** [comment]
Language C++ : [Programming Principles Practice Using C++](https://www.amazon.com/Programming-Principles-Practice-Using-C/dp/0321543726)

Algorithms: [Introduction to Algorithms](https://www.amazon.com/Introduction-Algorithms-3rd-MIT-Press/dp/0262033844)

And lots of practice, practice, and practice.

**Comment by harshitwalia** [comment]
Thanks. i have the cormen but never heard about the first book. by the way i have other books
